<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Elevator" Id="{41bd1c28-57fc-4e4f-9823-dbd6c73872aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Elevator EXTENDS A_Actuator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[super^();]]></ST>
    </Implementation>
    <Method Name="executeCmd" Id="{10b3bb40-4cfa-46b5-8d50-723dbb89ad53}">
      <Declaration><![CDATA[METHOD  executeCmd : BOOL
VAR_INPUT
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE eCmd OF
	eUP:
	eDOWN:
	eUP_TO_LIMIT:
	eDOWN_TO_LIMIT:
END_CASE]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Elevator">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Elevator.executeCmd">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="2" />
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>